# Generated by Django 3.2.4 on 2021-10-02 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_alter_book_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.CharField(choices=[('fiction', 'Fiction'), ('fantasy', 'Fantasy'), ('educational', 'Educational'), ('science_fiction', 'Science Fiction'), ('thriller', 'Thriller'), ('psychology', 'Psychology'), ('business_and_management', 'Business and Management'), ('productivity', 'Productivity'), ('comics_and_manga', 'Comics and Manga'), ('biography', 'Biography'), ('philosophy', 'Philosophy'), ('cooking', 'Cooking'), ('self-help', 'Self-help'), ('history', 'History'), ('science', 'Science'), ('math', 'Math'), ('finance_and_investment', 'Finance and Investment'), ('classics', 'Classics'), ('cooking', 'Cooking'), ('nutrition_and_health', 'Nutrition and Health'), ('programming', 'Programming'), ('other', 'Other')], default='other', max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='status',
            field=models.CharField(choices=[('read', 'read'), ('to-read', 'to-read'), ('currently-reading', 'currently-reading')], default='read', max_length=30, null=True),
        ),
    ]
