# Generated by Django 3.2.4 on 2021-10-08 16:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_name', models.CharField(max_length=100)),
                ('game_developer', models.CharField(max_length=100)),
                ('game_platform', models.CharField(choices=[('pc', 'PC'), ('console', 'Console'), ('other', 'Other')], default='pc', max_length=50)),
                ('game_release_date', models.DateField(null=True)),
                ('game_genre', models.CharField(max_length=50)),
                ('game_rating', models.CharField(choices=[('unrated', 'Unrated'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='unrated', max_length=40)),
                ('game_status', models.CharField(choices=[('played', 'Played'), ('wishlist', 'Wishlist'), ('playing', 'Playing'), ('unplayed', 'Unplayed')], default='unplayed', max_length=50)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
